ALTER TYPE "NotificationType" ADD VALUE 'CUSTOMER_CREATED';
ALTER TYPE "NotificationType" ADD VALUE 'CUSTOMER_UPDATED';
ALTER TYPE "NotificationType" ADD VALUE 'CUSTOMER_DELETED';
ALTER TYPE "NotificationType" ADD VALUE 'SETTINGS_UPDATED';
